# Generated by Django 6.0.5 on 2026-05-11 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Envios',
        ),
        migrations.DeleteModel(
            name='Inventario',
        ),
        migrations.DeleteModel(
            name='InventarioIngredientes',
        ),
        migrations.DeleteModel(
            name='Mensajes',
        ),
        migrations.DeleteModel(
            name='Producciones',
        ),
        migrations.DeleteModel(
            name='Repartidores',
        ),
        migrations.DeleteModel(
            name='Resenas',
        ),
        migrations.AlterModelOptions(
            name='carrito',
            options={},
        ),
        migrations.AlterModelOptions(
            name='carritodetalle',
            options={},
        ),
        migrations.AlterModelOptions(
            name='categorias',
            options={},
        ),
        migrations.AlterModelOptions(
            name='detallepedidos',
            options={},
        ),
        migrations.AlterModelOptions(
            name='ingredientes',
            options={},
        ),
        migrations.AlterModelOptions(
            name='pedidos',
            options={},
        ),
        migrations.AlterModelOptions(
            name='productoingrediente',
            options={},
        ),
        migrations.AlterModelOptions(
            name='productopromocion',
            options={},
        ),
        migrations.AlterModelOptions(
            name='productos',
            options={},
        ),
        migrations.AlterModelOptions(
            name='promociones',
            options={},
        ),
        migrations.AlterModelOptions(
            name='roles',
            options={},
        ),
        migrations.AlterModelOptions(
            name='ubicaciones',
            options={},
        ),
        migrations.AlterModelOptions(
            name='usuarios',
            options={},
        ),
    ]
