services:
  backend:
    build:
      context: ./backend
    container_name: cafesys_backend
    command: >
      sh -c "python manage.py migrate --fake-initial &&          
             python manage.py runserver 0.0.0.0:8081"
    volumes:
      - ./backend:/app
    ports:
      - "8081:8081"
    env_file:
      - ./backend/.env

  frontend:
    build:
      context: ./frontend
    container_name: cafesys_frontend
    command: >
      sh -c "npm install && 
             npx ng serve --host 0.0.0.0 --port 8082"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "8082:8082"