services:
  backend:
    build:
      context: ./backend
    container_name: cafesys_backend

    dns:
      - 8.8.8.8
      - 1.1.1.1
    
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1   # ← fuerza IPv4

    command: >
      sh -c "
      python manage.py migrate &&
      python -m apps.core.create_superuser &&
      python manage.py runserver 0.0.0.0:8081
      "
    volumes:
      - ./backend:/app
    ports:
      - "8081:8081"
    env_file:
      - ./backend/.env

  frontend:
    build:
      context: ./frontend
    container_name: cafesys_frontend
    command: >
      sh -c "
      npm install &&
      npx ng serve --host 0.0.0.0 --port 8082
      "
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "8082:8082"