services:
  - type: web
    name: cafesys-backend
    env: docker
    plan: free
    healthCheckPath: /
    dockerContext: ./backend
    dockerfilePath: ./backend/Dockerfile
    envVars:
      - key: DB_ENGINE
        value: django.db.backends.postgresql
      - key: DB_NAME
        value: postgres
      - key: DB_PORT
        value: "6543"
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_HOST
        sync: false
      - key: CORS_ALLOWED_ORIGINS
        value: https://cafe-sys.vercel.app
