# Generated by Django 6.0.5 on 2026-05-29 16:38

import apps.core.models.validators
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, validators=[apps.core.models.validators.validate_not_blank])),
                ('description', models.TextField(blank=True, null=True)),
                ('imageUrl', models.CharField(blank=True, max_length=255, null=True, validators=[apps.core.models.validators.validate_http_url])),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('alias', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(max_length=255, validators=[apps.core.models.validators.validate_not_blank])),
                ('reference', models.TextField(blank=True, null=True)),
                ('isDefault', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
                'db_table': 'locations',
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True, validators=[apps.core.models.validators.validate_not_blank])),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=100, validators=[apps.core.models.validators.validate_not_blank])),
                ('lastName', models.CharField(max_length=100, validators=[apps.core.models.validators.validate_not_blank])),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('passwordHash', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(8)])),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created_id', models.ForeignKey(blank=True, db_column='created_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_created', to='core.users')),
                ('modified_id', models.ForeignKey(blank=True, db_column='modified_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_modified', to='core.users')),
                ('role', models.ForeignKey(db_column='role_id', on_delete=django.db.models.deletion.PROTECT, related_name='users', to='core.roles')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
            },
        ),
        migrations.AddField(
            model_name='roles',
            name='created_id',
            field=models.ForeignKey(blank=True, db_column='created_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roles_created', to='core.users'),
        ),
        migrations.AddField(
            model_name='roles',
            name='modified_id',
            field=models.ForeignKey(blank=True, db_column='modified_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roles_modified', to='core.users'),
        ),
        migrations.CreateModel(
            name='Promotions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, validators=[apps.core.models.validators.validate_not_blank])),
                ('description', models.TextField(blank=True, null=True)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(100)])),
                ('discountType', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], max_length=20)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created_id', models.ForeignKey(blank=True, db_column='created_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotions_created', to='core.users')),
                ('modified_id', models.ForeignKey(blank=True, db_column='modified_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotions_modified', to='core.users')),
            ],
            options={
                'verbose_name': 'Promotion',
                'verbose_name_plural': 'Promotions',
                'db_table': 'promotions',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, validators=[apps.core.models.validators.validate_not_blank])),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('imageUrl', models.CharField(blank=True, max_length=255, null=True, validators=[apps.core.models.validators.validate_http_url])),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.PROTECT, related_name='products', to='core.categories')),
                ('created_id', models.ForeignKey(blank=True, db_column='created_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_created', to='core.users')),
                ('modified_id', models.ForeignKey(blank=True, db_column='modified_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_modified', to='core.users')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('orderStatus', models.CharField(choices=[('pending', 'Pending'), ('preparing', 'Preparing'), ('ready', 'Ready'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(db_column='location_id', on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='core.locations')),
                ('created_id', models.ForeignKey(blank=True, db_column='created_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_created', to='core.users')),
                ('modified_id', models.ForeignKey(blank=True, db_column='modified_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_modified', to='core.users')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='core.users')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=150, validators=[apps.core.models.validators.validate_not_blank])),
                ('body', models.TextField(validators=[apps.core.models.validators.validate_not_blank])),
                ('isRead', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created_id', models.ForeignKey(blank=True, db_column='created_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages_created', to='core.users')),
                ('modified_id', models.ForeignKey(blank=True, db_column='modified_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages_modified', to='core.users')),
                ('user', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='core.users')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'db_table': 'messages',
            },
        ),
        migrations.AddField(
            model_name='locations',
            name='created_id',
            field=models.ForeignKey(blank=True, db_column='created_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations_created', to='core.users'),
        ),
        migrations.AddField(
            model_name='locations',
            name='modified_id',
            field=models.ForeignKey(blank=True, db_column='modified_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations_modified', to='core.users'),
        ),
        migrations.AddField(
            model_name='locations',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='core.users'),
        ),
        migrations.CreateModel(
            name='Inventories',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('stock', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('minStock', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='core.products')),
                ('created_id', models.ForeignKey(blank=True, db_column='created_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventories_created', to='core.users')),
                ('modified_id', models.ForeignKey(blank=True, db_column='modified_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventories_modified', to='core.users')),
            ],
            options={
                'verbose_name': 'Inventory',
                'verbose_name_plural': 'Inventories',
                'db_table': 'inventories',
            },
        ),
        migrations.CreateModel(
            name='Drivers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('license', models.CharField(max_length=50, unique=True, validators=[apps.core.models.validators.validate_not_blank])),
                ('phone', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.MinLengthValidator(7)])),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created_id', models.ForeignKey(blank=True, db_column='created_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drivers_created', to='core.users')),
                ('modified_id', models.ForeignKey(blank=True, db_column='modified_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drivers_modified', to='core.users')),
                ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='driver', to='core.users')),
            ],
            options={
                'verbose_name': 'Driver',
                'verbose_name_plural': 'Drivers',
                'db_table': 'drivers',
            },
        ),
        migrations.AddField(
            model_name='categories',
            name='created_id',
            field=models.ForeignKey(blank=True, db_column='created_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories_created', to='core.users'),
        ),
        migrations.AddField(
            model_name='categories',
            name='modified_id',
            field=models.ForeignKey(blank=True, db_column='modified_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories_modified', to='core.users'),
        ),
        migrations.CreateModel(
            name='Vehicles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('plate', models.CharField(max_length=20, unique=True, validators=[apps.core.models.validators.validate_not_blank])),
                ('model', models.CharField(max_length=100, validators=[apps.core.models.validators.validate_not_blank])),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created_id', models.ForeignKey(blank=True, db_column='created_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles_created', to='core.users')),
                ('driver', models.ForeignKey(blank=True, db_column='driver_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='core.drivers')),
                ('modified_id', models.ForeignKey(blank=True, db_column='modified_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles_modified', to='core.users')),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicles',
                'db_table': 'vehicles',
            },
        ),
        migrations.CreateModel(
            name='Deliveries',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('deliveryStatus', models.CharField(choices=[('pending', 'Pending'), ('on_the_way', 'On The Way'), ('delivered', 'Delivered'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('departureAt', models.DateTimeField(blank=True, null=True)),
                ('deliveredAt', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(blank=True, db_column='driver_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='core.drivers')),
                ('order', models.OneToOneField(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='core.orders')),
                ('created_id', models.ForeignKey(blank=True, db_column='created_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries_created', to='core.users')),
                ('modified_id', models.ForeignKey(blank=True, db_column='modified_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries_modified', to='core.users')),
                ('vehicle', models.ForeignKey(blank=True, db_column='vehicle_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='core.vehicles')),
            ],
            options={
                'verbose_name': 'Delivery',
                'verbose_name_plural': 'Deliveries',
                'db_table': 'deliveries',
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.products')),
                ('created_id', models.ForeignKey(blank=True, db_column='created_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews_created', to='core.users')),
                ('modified_id', models.ForeignKey(blank=True, db_column='modified_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews_modified', to='core.users')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.users')),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
                'db_table': 'reviews',
                'unique_together': {('user', 'product')},
            },
        ),
        migrations.CreateModel(
            name='ProductsPromotions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, related_name='product_promotions', to='core.products')),
                ('promotion', models.ForeignKey(db_column='promotion_id', on_delete=django.db.models.deletion.CASCADE, related_name='product_promotions', to='core.promotions')),
                ('created_id', models.ForeignKey(blank=True, db_column='created_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_promotions_created', to='core.users')),
                ('modified_id', models.ForeignKey(blank=True, db_column='modified_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_promotions_modified', to='core.users')),
            ],
            options={
                'verbose_name': 'Product Promotion',
                'verbose_name_plural': 'Products Promotions',
                'db_table': 'products_promotions',
                'unique_together': {('product', 'promotion')},
            },
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('unitPrice', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, related_name='details', to='core.orders')),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.PROTECT, related_name='order_details', to='core.products')),
                ('created_id', models.ForeignKey(blank=True, db_column='created_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_details_created', to='core.users')),
                ('modified_id', models.ForeignKey(blank=True, db_column='modified_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_details_modified', to='core.users')),
            ],
            options={
                'verbose_name': 'Order Detail',
                'verbose_name_plural': 'Order Details',
                'db_table': 'order_details',
                'unique_together': {('order', 'product')},
            },
        ),
    ]
