# Generated by Django 6.0.5 on 2026-06-10 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roles',
            name='created_id',
        ),
        migrations.RemoveField(
            model_name='roles',
            name='modified_id',
        ),
        migrations.AlterField(
            model_name='users',
            name='role',
            field=models.CharField(choices=[('Admin', 'Administrator'), ('Driver', 'Driver'), ('Customer', 'Customer'), ('Employee', 'Employee')], default='Customer', max_length=20),
        ),
        migrations.DeleteModel(
            name='Inventories',
        ),
        migrations.DeleteModel(
            name='Roles',
        ),
    ]
