# Generated by Django 6.0.5 on 2026-06-13 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_promotions_imageurl_alter_promotions_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='role',
            field=models.CharField(max_length=50),
        ),
    ]
