# Generated by Django 6.0.5 on 2026-06-10 04:02

import apps.core.models.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_roles_created_id_remove_roles_modified_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotions',
            name='imageUrl',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[apps.core.models.validators.validate_http_url]),
        ),
        migrations.AlterField(
            model_name='promotions',
            name='discount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
    ]
