# Generated by Django 6.0.5 on 2026-06-10 20:56

import apps.core.models.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_users_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotions',
            name='discount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
    ]