# Generated by Django 6.0.5 on 2026-07-09 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_users_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='role',
            field=models.CharField(choices=[('Admin', 'Administrator'), ('Driver', 'Driver'), ('Customer', 'Customer'), ('Employee', 'Employee')], default='Customer', max_length=20),
        ),
    ]
