# Generated by Django (manual) on 2026-07-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_reviews_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotions',
            name='startDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='promotions',
            name='endDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]