# Generated by Django 6.0.5 on 2026-07-20 04:51

import apps.core.models.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_promotions_dates_optional'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drivers',
            name='created_id',
        ),
        migrations.RemoveField(
            model_name='drivers',
            name='modified_id',
        ),
        migrations.RemoveField(
            model_name='drivers',
            name='user',
        ),
        migrations.RemoveField(
            model_name='vehicles',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='vehicles',
            name='created_id',
        ),
        migrations.RemoveField(
            model_name='vehicles',
            name='modified_id',
        ),
        migrations.AddField(
            model_name='promotions',
            name='imageUrl',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[apps.core.models.validators.validate_http_url]),
        ),
        migrations.AlterField(
            model_name='orders',
            name='orderStatus',
            field=models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('preparing', 'Preparing'), ('ready', 'Ready'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='users',
            name='role',
            field=models.CharField(choices=[('Admin', 'Administrator'), ('Driver', 'Driver'), ('Customer', 'Customer'), ('Employee', 'Employee')], default='Customer', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='reviews',
            unique_together={('user', 'order')},
        ),
        migrations.DeleteModel(
            name='Deliveries',
        ),
        migrations.DeleteModel(
            name='Drivers',
        ),
        migrations.DeleteModel(
            name='Vehicles',
        ),
    ]
