# Generated by Django 6.0.5 on 2026-07-20 05:27

import apps.core.models.validators
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_drivers_created_id_remove_drivers_modified_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drivers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('license', models.CharField(max_length=50, unique=True, validators=[apps.core.models.validators.validate_not_blank])),
                ('phone', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.MinLengthValidator(7)])),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created_id', models.ForeignKey(blank=True, db_column='created_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drivers_created', to=settings.AUTH_USER_MODEL)),
                ('modified_id', models.ForeignKey(blank=True, db_column='modified_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drivers_modified', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='driver', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Driver',
                'verbose_name_plural': 'Drivers',
                'db_table': 'drivers',
            },
        ),
        migrations.CreateModel(
            name='Vehicles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('plate', models.CharField(max_length=20, unique=True, validators=[apps.core.models.validators.validate_not_blank])),
                ('model', models.CharField(max_length=100, validators=[apps.core.models.validators.validate_not_blank])),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created_id', models.ForeignKey(blank=True, db_column='created_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles_created', to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(blank=True, db_column='driver_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='core.drivers')),
                ('modified_id', models.ForeignKey(blank=True, db_column='modified_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicles',
                'db_table': 'vehicles',
            },
        ),
        migrations.CreateModel(
            name='Deliveries',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('deliveryStatus', models.CharField(choices=[('pending', 'Pending'), ('on_the_way', 'On The Way'), ('delivered', 'Delivered'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('departureAt', models.DateTimeField(blank=True, null=True)),
                ('deliveredAt', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created_id', models.ForeignKey(blank=True, db_column='created_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries_created', to=settings.AUTH_USER_MODEL)),
                ('modified_id', models.ForeignKey(blank=True, db_column='modified_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries_modified', to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='core.orders')),
                ('driver', models.ForeignKey(blank=True, db_column='driver_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='core.drivers')),
                ('vehicle', models.ForeignKey(blank=True, db_column='vehicle_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='core.vehicles')),
            ],
            options={
                'verbose_name': 'Delivery',
                'verbose_name_plural': 'Deliveries',
                'db_table': 'deliveries',
            },
        ),
    ]
